FROM node:18.17.1-alpine AS builder
ENV VITE_STAGE=prod
ENV VITE_API_URL https://vtal-api-portal-massas.onrender.com/

WORKDIR /usr/app/

COPY package.json .

RUN npm install

COPY . .

RUN npm run build


FROM nginx:1.21.0-alpine as production
COPY --from=builder /usr/app/dist /usr/share/nginx/html

COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD [ "nginx", "-g", "daemon off;" ]
