FROM node:18.17.1-alpine as base

RUN npm i -g pnpm

RUN apk add --no-cache nodejs

WORKDIR /usr/app/
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

FROM base as development
ENV VITE_STAGE dev
ENV VITE_API_URL https://vtal-api-portal-massas.onrender.com/
COPY . .
EXPOSE 5173
CMD ["pnpm", "dev"]